mv "影评 _ 《盛夏未来》--学会与不完美共生.html" "ColorsWorld_8月13日_影评 _ 《盛夏未来》--学会与不完美共生.html" 
mv "征集 _ 那些感到被接纳的时刻.html" "ColorsWorld_8月7日_征集 _ 那些感到被接纳的时刻.html" 
mv "故事 _ 我和森川老师（下）.html" "ColorsWorld_8月15日_故事 _ 我和森川老师（下）.html" 
mv "故事 _ 我和森川老师（上）.html" "ColorsWorld_8月10日_故事 _ 我和森川老师（上）.html" 
mv "故事 _ 看了《盛夏未来》的我，忽然想起17岁时我也暗恋过Gay.html" "ColorsWorld_8月6日_故事 _ 看了《盛夏未来》的我，忽然想起17岁时我也暗恋过Gay.html" 
mv "文学评论 _「S小说」与「百合」文化：女性主体的文学批评（章节0-1）.html" "ColorsWorld_8月25日_文学评论 _「S小说」与「百合」文化：女性主体的文学批评（章节0-1）.html" 
mv "文学评论 _ 「S小说」与「百合」文化：女性主体的文学批评（章节2）.html" "ColorsWorld_8月30日_文学评论 _ 「S小说」与「百合」文化：女性主体的文学批评（章节2）.html" 
mv "文学评论 _「S小说」与「百合」文化：女性主体的文学批评（章节3·完结）.html" "ColorsWorld_9月7日_文学评论 _「S小说」与「百合」文化：女性主体的文学批评（章节3·完结）.html" 
mv "特辑 _ 那些你可能会感兴趣的性少数YouTuber们.html" "ColorsWorld_8月20日_特辑 _ 那些你可能会感兴趣的性少数YouTuber们.html" 
mv "社交智库 _ SummerWave - SGS_Purple_CW线下Party来啦！.html" "ColorsWorld_7月29日_社交智库 _ SummerWave - SGS_Purple_CW线下Party来啦！.html" 
mv "神秘柜子 _ 原来，这个世界不是只有要求你改变的声音.html" "ColorsWorld_8月27日_神秘柜子 _ 原来，这个世界不是只有要求你改变的声音.html" 
mv "科普 _ “纸性恋”是真实存在的：无性恋者的性幻想.html" "ColorsWorld_8月12日_科普 _ “纸性恋”是真实存在的：无性恋者的性幻想.html" 
mv "线上议题 _ “恋爱关系中的女性主体意识”讨论笔记.html" "ColorsWorld_8月8日_线上议题 _ “恋爱关系中的女性主体意识”讨论笔记.html" 
mv "翻译 _ 你不是唯一讨厌性的人：“强制性性存在”（compulsory sexuality）.html" "ColorsWorld_8月29日_翻译 _ 你不是唯一讨厌性的人：“强制性性存在”（compulsory sexuality）.html" 
mv "翻译 _ 对于阿富汗LGBT+群体来说，“一切都已烟消云散”.html" "ColorsWorld_8月24日_翻译 _ 对于阿富汗LGBT+群体来说，“一切都已烟消云散”.html" 
mv "翻译 _ 当一个双性恋者在五十多岁时离了婚.html" "ColorsWorld_8月4日_翻译 _ 当一个双性恋者在五十多岁时离了婚.html" 
mv "访谈 _ 当直人进入性少数社群.html" "ColorsWorld_7月22日_访谈 _ 当直人进入性少数社群.html" 
mv "读书会 _ 朱迪斯·巴特勒《脆弱不安的生命：哀悼与暴力的力量》.html" "ColorsWorld_7月31日_读书会 _ 朱迪斯·巴特勒《脆弱不安的生命：哀悼与暴力的力量》.html" 
mv "读书会讨论实录 _ 我们该如何回应他者的暴力？.html" "ColorsWorld_9月3日_读书会讨论实录 _ 我们该如何回应他者的暴力？.html" 
mv "重温 _ 他人即地狱：恐同与内化恐同 (2021_9_28 下午10_45_42).html" "ColorsWorld_8月22日_重温 _ 他人即地狱：恐同与内化恐同 (2021_9_28 下午10_45_42).html" 
mv "重温 _ 台湾同志运动史回顾.html" "ColorsWorld_8月31日_重温 _ 台湾同志运动史回顾.html" 
mv "重温 _ 在巴厘岛下一场彩虹色的雪.html" "ColorsWorld_8月5日_重温 _ 在巴厘岛下一场彩虹色的雪.html" 
mv "重温 _ 她不会永远沉默：中文男权语境下的女性表达.html" "ColorsWorld_8月14日_重温 _ 她不会永远沉默：中文男权语境下的女性表达.html" 
mv "重温 _ 平等无需相等：谈波伏娃与《第二性》.html" "ColorsWorld_8月26日_重温 _ 平等无需相等：谈波伏娃与《第二性》.html" 
mv "重温 _ 我们需要怎样的_厕所革命_？.html" "ColorsWorld_9月9日_重温 _ 我们需要怎样的_厕所革命_？.html" 
mv "重温 _ 我想为自己定制一种性别.html" "ColorsWorld_7月18日_重温 _ 我想为自己定制一种性别.html" 
mv "重温 _ 浅析我国历史中主流文化对同性恋的态度变化.html" "ColorsWorld_9月5日_重温 _ 浅析我国历史中主流文化对同性恋的态度变化.html" 
mv "重温 _ 解放与压迫的迷思：伊朗女性为什么会支持伊斯兰革命？.html" "ColorsWorld_8月9日_重温 _ 解放与压迫的迷思：伊朗女性为什么会支持伊斯兰革命？.html" 
mv "重温 _ 闺阁情事：古代女同现象简述.html" "ColorsWorld_8月1日_重温 _ 闺阁情事：古代女同现象简述.html" 
mv "隐蔽派对Vol.06｜“我把整个性取向光谱都流了一遍”.html" "ColorsWorld_8月11日_隐蔽派对Vol.06｜“我把整个性取向光谱都流了一遍”.html" 
mv "隐蔽派对Vol.7｜“我不会因为你不喜欢我的长相而自卑”.html" "ColorsWorld_9月1日_隐蔽派对Vol.7｜“我不会因为你不喜欢我的长相而自卑”.html" 
